### ISSUE TITLE
ImpDyn ??

### ISSUE THREAD

**Issue by antonagafonov** [facebookresearch/AutoAvatar#1]
Hi,
Great paper.
What is inside ImpDyn directory?

I am trying to implement your code.

In clone instructions, the link is missing instead https://github.com/facebookresearch/AutoAvatar/ link there is a https://github.com link.

Thanks

Anton

**Comment by zqbai-jeremy** [comment]
Hi,

Really sorry for the bugs in readme. "ImpDyn" should be "AutoAvatar", which is a bug caused by renaming and has been fixed. The link in clone instruction is also updated.
Thank you very much for bringing that to my attention!

Best regards,

Ziqian Bai

**Comment by antonagafonov** [comment]
Hi,
Thanks for the fix.
Another one I think in the Data Preprocess step 
While running this : 

cd AutoAvatar
export PYTHONPATH=<workspace_folder>/AutoAvatar
python exps/PosedDecKNN_dPoses_dHs/implicit_train_dfaust.py --ws_dir <workspace_folder> --configs_path configs/PosedDecKNN_dPoses_dHs/AutoRegr.yaml --configs_path_rollout configs/PosedDecKNN_dPoses_dHs/AutoRegr_Rollout2.yaml

Getting this: 

Traceback (most recent call last):
  File "AutoAvatar/data/DFaust_generate.py", line 489, in <module>
    DFaust_smplh_to_smpl(
  File "AutoAvatar/data/DFaust_generate.py", line 92, in DFaust_smplh_to_smpl
    os.mkdir(out_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'AutoAvatar/DFaust/smpl_poses'

I don't have smpl_poses in DFaust directory.

Please help me to solve .

Thanks ,
Anton

**Comment by zqbai-jeremy** [comment]
Would you mind to share the current folder structure you have and the <workspace_folder> you are using? Thanks!

**Comment by antonagafonov** [comment]
Hi,

Here attached <worspase_folder> dir tree:

├── AutoAvatar
│   ├── assets
│   ├── configs
│   │   └── PosedDecKNN_dPoses_dHs
│   ├── data
│   ├── exps
│   │   └── PosedDecKNN_dPoses_dHs
│   ├── models
│   │   ├── PosedDecKNN_dPoses_dHs
│   │   └── std
│   └── utils
│       └── __pycache__
├── DFaust
│   ├── DFaust_67
│   │   ├── 50002
│   │   ├── 50004
│   │   ├── 50007
│   │   ├── 50009
│   │   ├── 50020
│   │   ├── 50021
│   │   ├── 50022
│   │   ├── 50025
│   │   ├── 50026
│   │   └── 50027
│   └── scans
│       └── 50002
│           ├── chicken_wings
│           ├── hips
│           ├── jiggle_on_toes
│           ├── jumping_jacks
│           ├── knees
│           ├── light_hopping_loose
│           ├── light_hopping_stiff
│           ├── one_leg_jump
│           ├── one_leg_loose
│           ├── punching
│           ├── running_on_spot
│           ├── shake_arms
│           ├── shake_hips
│           └── shake_shoulders
├── external
│   └── human_body_prior
│       ├── src
│       │   ├── human_body_prior
│       │   │   ├── body_model
│       │   │   │   ├── parts_segm
│       │   │   │   │   └── smplh
│       │   │   │   └── __pycache__
│       │   │   ├── data
│       │   │   ├── evaluations
│       │   │   ├── models
│       │   │   ├── __pycache__
│       │   │   ├── tools
│       │   │   │   └── __pycache__
│       │   │   ├── train
│       │   │   │   └── V02_05
│       │   │   └── visualizations
│       │   └── human_body_prior.egg-info
│       ├── support_data
│       │   └── dowloads
│       ├── tests
│       │   └── samples
│       └── tutorials
└── SMPL
    └── 50002_pretrained
        ├── ckpt
        └── net_def

**Comment by zqbai-jeremy** [comment]
In the command:
python data/DFaust_generate.py --ws_dir <workspace_folder>
The <workspace_folder> should be the parent folder of DFaust, SMPL, AutoAvatar. Is that the command you used?

From the error msg: FileNotFoundError: [Errno 2] No such file or directory: 'AutoAvatar/DFaust/smpl_poses'
It looks like you are using AutoAvatar folder as the --ws_dir argument.

**Comment by antonagafonov** [comment]
Hi,
DFaust, SMPL, AutoAvatar are in the same directory, but I don't have smpl_poses inside DFaust dir.
Where I can get it from, I think I some how missed its installation.

Thanks

**Comment by zqbai-jeremy** [comment]
smpl_poses folder inside DFaust should be generated by the code data/DFaust_generate.py.
Would you mind to share the exact command you used and the name of the folder which includes DFaust, SMPL, AutoAvatar?
The folder which includes DFaust, SMPL, AutoAvatar should be the <workspace_folder> input as the argument --ws_dir

**Comment by antonagafonov** [comment]
Hi,

The command I'm running is :

python data/DFaust_generate.py  --ws_dir GitHub

Parrent of DFaust, SMPL, AutoAvatar is GitHub.

Attached screenshot of the command:

![image](https://user-images.githubusercontent.com/63194980/198944362-686dd6f1-b172-4fcd-a052-2f42a4131651.png)

**Comment by zqbai-jeremy** [comment]
Better use absolute path. Your current pwd is AutoAvatar. So need to either use absolute path or ../GitHub
But relative path may cause unexpected issues, so personally I suggest to use absolute path.

**Comment by antonagafonov** [comment]
OK,

Used absolute path.

Passed to the next error:

Traceback (most recent call last):
  File "data/DFaust_generate.py", line 489, in <module>
    DFaust_smplh_to_smpl(
  File "data/DFaust_generate.py", line 100, in DFaust_smplh_to_smpl
    bm = BodyModel(bm_fname=bm_fname, num_betas=num_betas, num_dmpls=num_dmpls, dmpl_fname=dmpl_fname)#.cuda(gpu_id)
  File "/home/aa/Documents/GitHub/AutoAvatar/external/human_body_prior/src/human_body_prior/body_model/body_model.py", line 59, in __init__
    smpl_dict = np.load(bm_fname, encoding='latin1')
  File "/home/aa/miniconda3/envs/impdyn/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/aa/Documents/GitHub/SMPL/smplh/male/model.npz'

Looks like some SMPL models missing.

Thanks,

**Comment by antonagafonov** [comment]
Now I see that SMPL-H and DMPLS are missing from the directory.

**Comment by zqbai-jeremy** [comment]
Oh that's for setting up AMASS. Really sorry for missing that part. I'm trying to add additional instructions for it.

**Comment by antonagafonov** [comment]
OK.

Thanks for the support.

I succeeded to run this command after downloading the missing SMPL-H and DMPL.

Thanks,

**Comment by antonagafonov** [comment]
Hi,
In trainbox.py is better to use:
os.makedirs()
instead:
 os.mkdir()

because logs is not exists the firs time.

Anton

**Comment by antonagafonov** [comment]
Hi,

Also in implicit_eval_dfaust.py neet to change to os.makedirs() in line 81.

Because logs_test not exist.

AA

**Comment by zqbai-jeremy** [comment]
Really sorry for my late reply and thanks for your comments! Just updated instructions of "AMASS setup" and os.makedirs().
